services:
  - type: web
    name: crawl-engine
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: standard
    preDeployCommand: "./node_modules/.bin/prisma migrate deploy"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: CHROME_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: ENCRYPTION_KEY
        sync: false
